spring:
  profiles:
    active: dev

  sql:
    init:
      mode: never
      platform: postgresql

  datasource:
    url: jdbc:postgresql://localhost:5432/picnest
    username: ENC(nwq/5pkZWyETjOhE8qh2dTzMmQWsX+E8)
    password: ENC(8qA0tC2gRuAaCeowLt0BNO+JzwWPIFJ9)

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(FupNfUyPCMacs0SoZxwsuAbXDrRk/yInYnu+ZTrixaJquUYXvEu5Iw==)
    password: ENC(uIGFNShjldNUheHtZq7lxYAyA5I1fNCaajK/XXFhMhs=)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ENC(Geib8wQUjPkm5MhtrbZSHXrn9lmo3V2WDcN7PRYv5VY=)
            client-secret: ENC(XQscTo0Gt7EL/m6AI8qfcNlOeEGex2pxtzexOZPtpFqvz2MuJRpfEfs00n9JdGXOhkrENvhrLIM=)
            scope:
              - email
          google:
            client-id: ENC(DqfWJLE7ms4T7HRZ6GlHAkpFyFjh9QmmpHYPWTQqT8Ch1ZOJbA6Z91JtZjckdSlPyunn88FmVDzquXHL0E/8/W13q2gPr8nMbp6O/yZOG8XmnouRxhQAxw==)
            client-secret: ENC(1ivx+UPf0OM1Kb01JAWZ8mK9mseqC+PkjC37wdczfOR8361bYTuqHDXFooekFPJ6)
            scope:
              - email
              - profile
          vk:
            client-id: ENC(lrQk6wgxUsKeo2JujsrSqt0JZVF+W5TO)
            client-secret: ENC(jSQamdxRx11qJq4wqP2sYsKdZsJ21AUOc1cudnhtsiA=)
            client-name: Vkontakte
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: email
          yandex:
            client-id: ENC(EUPv/bJ7mqRiRxee279xt1+uvzBj713eEhyKeHI18ptTFILd6RR1fauWSnqrvx3u)
            client-secret: ENC(IbdZtaCg+uGMhhP72I4+gWwWNGjQ8ousXaAa7u+zIlc0SZtA2p49l09ZzLz/Kiyk)
            client-name: Yandex
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
          gitlab:
            client-id: ENC(Y+4WGd1Brp+b5QlMp8ZMeKGwQVARLR/EXcMA99/IJG+fNm+eXR6nSlq5hCM/OjYRIK8QBC+ElnPxY/l+Br0JFPDSn3GJa14qXmxfdd2HRdQ=)
            client-secret: ENC(T0sDjx6TjUIQ2p9Y6wMvUKFAZPZwuTayE0PbUusfwOPkqUrjlhS//tGG1vN23/yg89o8qPL3osM6+GcJL7LvjrLsLyDQLpQICsuTgSFgWpg=)
            client-name: GitLab
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: read_user
        provider:
          vk:
            authorization-uri: https://oauth.vk.com/authorize
            token-uri: https://oauth.vk.com/access_token
            user-info-uri: https://api.vk.com/method/users.get?v=8.1
            user-name-attribute: response
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: login
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/api/v4/user
            user-name-attribute: email

remember-me:
  key: remember-me-key
  cookie-name: picnest-remember-me

server:
  tomcat:
    max-http-form-post-size: 50MB
  servlet:
    encoding:
      charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
      enabled: true # Enable http encoding support
      force: true

register:
  token-expiration-time: 86400000
  confirm-url: https://javaprojects.ru/picnest/register/confirm

password-reset:
  token-expiration-time: 86400000
  confirm-url: https://javaprojects.ru/picnest/profile/reset-password

change-email:
  token-expiration-time: 86400000
  confirm-url: https://javaprojects.ru/picnest/profile/change-email/confirm

content-path:
  pictures: ./picnest/content/pictures/
  pictures-uri: /picnest/content/pictures/
  avatars: ./picnest/content/avatars/

locale:
  supported: en,ru
  default: ru

logging:
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: logs/picnest.log
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr([%mdc]){yellow} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}'
    file: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%mdc] - %msg%n'

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: 123456Gtx
