spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  sql:
    init:
      mode: always
      encoding: UTF-8
      platform: h2
      data-locations: classpath:data.sql
  datasource:
    url:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  web:
    resources:
      static-locations: file:src/main/resources/static
      chain:
        cache: false

register:
  confirm-url: http://localhost:8080/register/confirm

password-reset:
  confirm-url: http://localhost:8080/profile/reset-password

change-email:
  confirm-url: http://localhost:8080/profile/change-email/confirm

content-path:
  pictures: ./picnest/content/pictures/
  pictures-uri: /picnest/content/pictures/
  avatars: ./picnest/content/avatars/

locale:
  supported: en,ru
  default: en
